//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyMCE.FileExplorer.Web.Core.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TinyMCE.FileExplorer.Web.Core.Resources.Views.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de criação.
        /// </summary>
        public static string ArchiveViewDateCreated {
            get {
                return ResourceManager.GetString("ArchiveViewDateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover.
        /// </summary>
        public static string ArchiveViewDelete {
            get {
                return ResourceManager.GetString("ArchiveViewDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string ArchiveViewDownload {
            get {
                return ResourceManager.GetString("ArchiveViewDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string ArchiveViewName {
            get {
                return ResourceManager.GetString("ArchiveViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caminho.
        /// </summary>
        public static string ArchiveViewPath {
            get {
                return ResourceManager.GetString("ArchiveViewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar.
        /// </summary>
        public static string ArchiveViewPreview {
            get {
                return ResourceManager.GetString("ArchiveViewPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar.
        /// </summary>
        public static string ArchiveViewSelect {
            get {
                return ResourceManager.GetString("ArchiveViewSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho.
        /// </summary>
        public static string ArchiveViewSize {
            get {
                return ResourceManager.GetString("ArchiveViewSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de arquivos.
        /// </summary>
        public static string ArchiveViewSummary {
            get {
                return ResourceManager.GetString("ArchiveViewSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de arquivos:.
        /// </summary>
        public static string ArchiveViewTotalFiles {
            get {
                return ResourceManager.GetString("ArchiveViewTotalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recolher pastas.
        /// </summary>
        public static string ToolbarCollapseFolderExplorer {
            get {
                return ResourceManager.GetString("ToolbarCollapseFolderExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover pasta.
        /// </summary>
        public static string ToolbarDeleteFolder {
            get {
                return ResourceManager.GetString("ToolbarDeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expandir pastas.
        /// </summary>
        public static string ToolbarExpandFolderExplorer {
            get {
                return ResourceManager.GetString("ToolbarExpandFolderExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurar arquivo.
        /// </summary>
        public static string ToolbarFindFile {
            get {
                return ResourceManager.GetString("ToolbarFindFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova pasta.
        /// </summary>
        public static string ToolbarNewFolder {
            get {
                return ResourceManager.GetString("ToolbarNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar pastas.
        /// </summary>
        public static string ToolbarRefreshFolderExplorer {
            get {
                return ResourceManager.GetString("ToolbarRefreshFolderExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternar exibição.
        /// </summary>
        public static string ToolbarToggleFolderExplorer {
            get {
                return ResourceManager.GetString("ToolbarToggleFolderExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar arquivos.
        /// </summary>
        public static string ToolbarUploadFiles {
            get {
                return ResourceManager.GetString("ToolbarUploadFiles", resourceCulture);
            }
        }
    }
}
